# Generated by Django 3.0.2 on 2020-12-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pb1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb1',
            name='remarks',
            field=models.TextField(verbose_name=''),
        ),
    ]
