# Generated by Django 3.0.2 on 2020-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201224_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pb2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pb3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pb4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pb5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pb6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pb7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('remarks', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
    ]
